require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  CountComments: false
  Max: 32

Metrics/ClassLength:
  CountComments: false
  Max: 200

Metrics/ParameterLists:
  Max: 10

Naming/AccessorMethodName:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: always_ignore

Layout/EndOfLine:
  EnforcedStyle: lf

Naming/VariableNumber:
  EnforcedStyle: snake_case

Naming/PredicateName:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/Date:
  Enabled: false

Performance/Casecmp:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false