default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] { 5 } %>

development:
  <<: *default
  database: mail_track_service_development

test:
  <<: *default
  database: mail_track_service_test

production:
  <<: *default
  database: mail_track_service_production
